# -*- coding: utf-8 -*-
# Part of BiztechCS. See LICENSE file for full copyright and licensing details.

{
    'name': 'Service',
    'author': 'AppJetty',
    'version': '11.0.1.0.0',
    'description': 'Service & web',
    'category': 'service',
    'website': 'https://www.biztechconsultancy.com/',
    'depends': ['base_setup', 'sale','website', 'auth_signup', 'auth_oauth', 'crm', 'website_quote','delivery','hr','mass_mailing','theme_crafito','web'],
    'data': [
        'data/service_data.xml',
        'security/service_security.xml',
        'security/ir.model.access.csv',
        'wizard/schedule_work_view.xml',
        'wizard/open_confirmation_view.xml',
        'wizard/attached_wspc_report_view.xml',
        'wizard/service_move_wiz.xml',
        'wizard/truck_warehouse.xml',
        'views/customer_information_views.xml',
        'views/equipment_views.xml',
        'views/partner_filter_extend_view.xml',
        'views/website_template.xml',
        'data/service_demo.xml',
        'views/biztech_service_report.xml',
        'views/report_service_workorder.xml',
        'views/res_company_extend.xml',
        "data/website_quote_template_extend.xml",
        'views/report_service_quotation.xml',
        'views/website_quote_template_extend.xml',
        'views/sale_payment_method_view.xml',
        'data/delivery_method.xml',
        'data/custom_mail_layout_template.xml',
        'views/theme_crafito_extend.xml',
        'data/customer_create_mail_template.xml',
        'views/account_invoice_extend.xml',
        'views/purchase_extend_sequence_view.xml',
        'views/template.xml',
        'views/stock_picking_include_service.xml',
        'views/equiepment_view_change.xml',
        'views/custom_mail_template.xml',
        'views/product_form_view_count_sale_order.xml',
        'views/product_part_access_view.xml'
    ],
    'installable': True,
    'auto_install': False,
}
